makerdao/mkr-mcd-spec

.gitmodules, Dockerfile, Jenkinsfile, Makefile, README.md, media/sphinx-docs/conf.py, media/sphinx-docs/index.rst
This will serve as running documentation of progress made, as well as documentation of the entire MKR system.
=> Generate Sphinx Read-The-Docs from model

cdp-core.md, collateral.md, kmcd-driver.md, kmcd.md
This will not kompile until the necessary changes to K are merged and the submodule is bumped, but I wanted to solicit feedback early.
=> Semantics of Flip

cdp-core.md, collateral.md, dai.md, kmcd-driver.md, kmcd.md, rates.md, stabilize.md
Fixes: #35 
What this does at a high level:
* moves logic relating to exceptions, state reverts, and authentiation entirely into kmcd-river.md.
* fixes various low level issues involving authorization in various steps
* unifies the negative cases into fewer rules
* cleans up some stuff relating to incorrect "init" functions
* cleans up the configuration
* adds logic for function calls
=> Control flow refactoring

collateral.md
=> Semantics of Gem

kmcd-driver.md, stabilize.md
=> Semantics of Flap and Flop

rates.md
=> Semantics of Pot

stabilize.md
Fixes: #65
Also includes a few minor bugfixes for Flap and Flop
=> Semantics of Vow

README.md, end.md, flip.md, flop.md, vow.md
Fixes: #88 
This PR updates the README with better summaries of what each file does for the sake of the generated GitHub pages.
It also includes a summary of how to run an individual test.
=> Documentation - update README and formatting

kmcd-driver.md, tests/attacks/lucash-flap-end.mcd.expected, tests/attacks/lucash-flip-end.mcd.expected, tests/attacks/lucash-pot-end.mcd, tests/attacks/lucash-pot-end.mcd.expected, tests/attacks/lucash-pot.mcd.expected
This Pr also removes a redundant initialization in one of the tests
=> Log exceptions

cat.md
Also fix issue with over-lapping rule because of how return values are handled now.
=> Update deps - latest working K version

tests/attacks/lucash-flap-end.mcd, tests/attacks/lucash-flap-end.random.mcd, tests/attacks/lucash-flip-end.mcd, tests/attacks/lucash-flip-end.random.mcd, tests/attacks/lucash-pot-end.mcd, tests/attacks/lucash-pot-end.random.mcd, tests/attacks/lucash-pot.mcd, tests/attacks/lucash-pot.random.mcd
This simply adds `assert` to all attack examples
=> added assert to examples

Dockerfile, Makefile, join.md, kmcd, kmcd-prelude.md, mcd-pyk.py, spot.md, tests/attacks/lucash-flap-end.mcd.expected, tests/attacks/lucash-flap-end.random.mcd, tests/attacks/lucash-flap-end.random.mcd.expected, tests/attacks/lucash-flip-end.mcd.expected, tests/attacks/lucash-flip-end.random.mcd, tests/attacks/lucash-flip-end.random.mcd.expected, tests/attacks/lucash-pot-end.mcd.expected, tests/attacks/lucash-pot-end.random.mcd, tests/attacks/lucash-pot-end.random.mcd.expected, tests/attacks/lucash-pot.mcd.expected, tests/attacks/lucash-pot.random.mcd, tests/attacks/lucash-pot.random.mcd.expected
This switches us over to use bytestrings for witnessing the attacks, which gives us more granularity in each decision point of the attack generation.
=> Bytes witnesses of generated attacks

kmcd-props.md
Vat invariants + hopefully some more properties
=> More properties

LICENSE, README.md
Adding license and updating links in README
=> Publication cleanup

.gitignore, Makefile, mcd-pyk.py, tests/attacks/lucash-flap-end.random.mcd.expected, tests/attacks/lucash-flip-end.random.mcd.expected, tests/attacks/lucash-pot-end.random.mcd.expected
Confirmed that we can now generate the same attacks using the python generator (and an initial seed).
=> Python generated attacks with command-line interface

mcd-pyk.py
=> reorg caller to be closer to our solidity test patterns

kmcd-prelude.md, spot.md, tests/attacks/lucash-flap-end.mcd.expected, tests/attacks/lucash-flap-end.random.mcd.expected, tests/attacks/lucash-flip-end.mcd.expected, tests/attacks/lucash-flip-end.random.mcd.expected, tests/attacks/lucash-pot-end.mcd.expected, tests/attacks/lucash-pot-end.random.mcd.expected, tests/attacks/lucash-pot.mcd.expected, tests/attacks/lucash-pot.random.mcd.expected, tests/fixes/debtBoundDSR.mcd.expected, tests/fixes/potChiPieDai.mcd.expected
This was from @iamchrissmith , but it was made into a non-`master` branch, so it could not be tested by our CI system.
See the closed #164. I believe it's already been approved, so just needs re-approval.
=> Init spot with mat

cat.md, dai.md, flap.md, flip.md, flop.md, join.md, kmcd-prelude.md, kmcd-props.md, mcd-pyk.py, spot.md, tests/attacks/lucash-flap-end.mcd.expected, tests/attacks/lucash-flap-end.random.mcd.expected, tests/attacks/lucash-flip-end.mcd.expected, tests/attacks/lucash-flip-end.random.mcd.expected, tests/attacks/lucash-pot-end.mcd.expected, tests/attacks/lucash-pot-end.random.mcd.expected, tests/attacks/lucash-pot.mcd.expected, tests/attacks/lucash-pot.random.mcd.expected, tests/fixes/debtBoundDSR.mcd.expected, tests/fixes/potChiPieDai.mcd.expected, vat.md, vow.md
-   Bounds checks on `Vow` contract which enforce non-negative number, and cleanup of side-conditions in some cases.
-   Make sure we aren't overwriting the existing function-call events with custom events that are logged.
-   Add in "unimplemented" custom log assertions.
-   Make sure we have a post-state even when a violation is found (for making post-state delta for assertion generation).
=> Cleanups to model

Makefile, flap.md, flip.md, flop.md, tests/attacks/blocked-flop.mcd.expected, vow.md
This implements the changes from: makerdao/dss#110 and makerdao/dss#109.
I've marked it as a draft, so that it can be reviewed/merged after the other two are done.
=> Changes to auction contracts

.gitmodules, Dockerfile, Jenkinsfile, Makefile
This just runs the MKR tests on CI to make sure we have all the dependencies setup correctly ahead of time.
=> Run MKR tests on CI

.gitmodules, Dockerfile, Jenkinsfile, Makefile, kmcd, kmcd-driver.md, kmcd-prelude.md, mcd-pyk.py, tests/attacks/blocked-flop.mcd.run.expected, tests/attacks/lucash-flap-end.mcd.run.expected, tests/attacks/lucash-flap-end.random.mcd.run.expected, tests/attacks/lucash-flip-end.mcd.run.expected, tests/attacks/lucash-flip-end.random.mcd.run.expected, tests/attacks/lucash-pot-end.mcd.run.expected, tests/attacks/lucash-pot-end.random.mcd.run.expected, tests/attacks/lucash-pot.mcd.run.expected, tests/attacks/lucash-pot.random.mcd.run.expected, tests/fixes/attackPrelude.mcd.run.expected, tests/fixes/debtBoundDSR.mcd.run.expected, tests/fixes/deployPrelude.mcd.run.expected, tests/fixes/potChiPieDai.mcd.run.expected
This integrates and updates the build system to make it work with KEVM's repo.
=> Integrate kevm into mkr-mcd-spec
