makerdao/mkr-mcd-spec

Makefile
README.md
mkr-mcd-data.md
mkr-mcd.md

Questions:
-   `Wad`, `Ray`, and `Rad` are used in the specification for various operations of mixed precision. The abstract model may benefit from ignoring the precision and using unbounded integers (to model how the "ideal" system would behave).
-   I see several definitions of `struct Ilk` and `struct Urn`, with slightly different data fields. Should these be distinguished or are they morally the same? For now, I'm sorting them differently based on where they come from (ie. `VatIlk` and `VatUrn`).
-   Currently, we store several `Map` of `(address => ...)` in the `<vat>` configuration. Would we benefit by inverting the logic to have a single map of `(address => UserVat)`, where `UserVat` contains all the data relevant for that user?

Initial model of `Vat` contract

---

cdp-core.md
collateral.md
kmcd.md

unlike uint256, Bytes32 is an array of bytes and generally represents strings. So here we use String everywhere the solidity code references bytes32.

Use String to represent Solidity bytes32 types

---

kmcd-driver.md
vat.md

This code essentially assumes that any method that doesn't have the note modifier will explicitly rewrite the `frame-events` cell to the exact events emitted by that call frame.

Note modifier

---

Jenkinsfile
Makefile
cat.md
dai.md
end.md
flap.md
flip.md
flop.md
gem.md
join.md
jug.md
kmcd-driver.md
pot.md
spot.md
strip-erroneous-labels.sh
vat.md
vow.md

-   Enable `Debug` build by default for speed.
-   Strip out erroneous labels added with haskell backend because of K-TERM hack in definition manually.
-   `transact` should have a source address, which is what `msg-sender` and `this` is set to initially.
-   `call` only updates `this`, but `msg-sender` remains unchanged.
-   Single global `owise` rule for throwing exceptions instead of per-file rules.

Transact corrections, udpates to build harness

---

cat.md
dai.md
end.md
flap.md
flip.md
flop.md
gem.md
join.md
jug.md
pot.md
spot.md
vat.md
vow.md

-   Organize each semantics file slightly (generic infra first, then datastructures, then file-able fields, then events, then semantics).
-   Add documentation for all data-structures.
-   Add `file` methods as `auth` methods in the model, and documentation of each file-able parameter.
-   Some simple changes to naming schemes.

Add code for `file` methods, cleanups

---

cat.md
dai.md
end.md
flap.md
flip.md
flop.md
gem.md
join.md
jug.md
kmcd-driver.md
kmcd.md
pot.md
spot.md
vat.md
vow.md

-   Renames some cells to use `-` instead of camel-case (for consistency).
-   Removes the `<*-addr>` cells, which are largely unused.
-   Checks for authorization by looking for containment in the added `<*-wards>` cells at the `call` boundaries.
-   Uses sort `AdminStep` for all steps which `exception` shouldn't pass through (eg. the next transaction).

Global authentication/ward scheme

---

.gitignore
Jenkinsfile
Makefile
end.md
gem.md
join.md
jug.md
kmcd-driver.md
pot.md
spot.md
tests/attacks/lucash-pot-end.mcd
tests/attacks/lucash-pot-end.mcd.expected
vat.md

Fixes: #84 
-   Several bug-fixes discovered while implementing lucash-pot-end attack.
-   Add state initializers for setting up for attack sequence.
-   Add lucash-pot-end attack and expected output, confirmed locally that without the associated fix the attack goes through.
-   Setup testing harness for KMCD simulations.
Note that in the test expected output, the `Pot . file dsr` step does _not_ show up in the `<events>` output, because that step gets rolled back (because of the extra check against `live`, which is set to `false` by the added `Pot . cage`). Additionally, in `<vat-dai>` we can see that `Alice` and `Bobby` end up with the same amount of dai.

Attack test: lucash-pot-end

---

end.md
flip.md
jug.md
kmcd-driver.md
kmcd.md
tests/attacks/lucash-flip-end.mcd
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
vat.md

-   Test case: `tests/attacks/lucash-flip-end`
-   Updates to how `call`/`transact` harness work.
-   Formatting fixes to `flip.md`.
-   Remove useless `InitStep` sort.
-   Fixes to some `init` methods.

Lucash flip end - fixes to semantics and new test case

---

kmcd-driver.md
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot.mcd.expected

This PR logs `TimeStep` events and includes the `<current-time>` in the log, which facilitates reading the `<events>` cell at the end of an execution.

Time step log

---

flop.md
tests/attacks/lucash-flap-end.mcd.expected
tests/attacks/lucash-flap-end.random.mcd.expected
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-flip-end.random.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot-end.random.mcd.expected
tests/attacks/lucash-pot.mcd.expected
tests/attacks/lucash-pot.random.mcd.expected

Everett and Musab,
I couldn't find where we had updated the Flop spec to account for the bug fix we did, so I took a shot and making the update myself.  I was able to run:
`make deps` (no changes)
`make build -j12` (got though some missing pieces and then didn't fail)
`make test-execution -j12` (identified missing state, then said no changes from `expected`)
Please let me know if there are other things I should run to ensure this is correct and how I could make any improvements to the changes

update flop spec and tests to account for yank-suck changes

---

kmcd
kmcd-driver.md
kmcd-prelude.md
kmcd-props.md
tests/attacks/lucash-flap-end.mcd.expected
tests/attacks/lucash-flap-end.random.mcd.expected
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-flip-end.random.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot-end.random.mcd.expected
tests/attacks/lucash-pot.mcd.expected
tests/attacks/lucash-pot.random.mcd.expected

Makes it easier to see why a given trace violates some properties by:
-   Turning properties into `ViolationFSM`s instead of having them just be boolean formulas,
-   Having each property being checked be in its own entry in a `Map` with a given name.

Separate and name violations

---

Makefile
kmcd

There isn't any need for the jvaa backend in this repo, indeed, this definition uses features that it does not support (so running anything on Java backend will crash anyway).

Makefile, kmcd: remove java backend

---

kmcd-prelude.md

Currently we're blocked on updating the Frontend version because the Haskell backend is now (correctly) throwing a warning about unsupported symbolic choice variables `?` variables.
This PR disables those variables, which leaves us with functional semantics for those choice functions (good), but puts no constraints on the results of those functions (bad).
So this isn't incorrect, it's just not as "tight" as we would like. But it lets us update to newest K.
On the version of K this uses, the Haskell backend just does the wrong thing anyway, since it doesn't correctly support `?` variables. So this will at least make it do something sensible (albeit not quite what's desired).

Remove symbolic choice

---

Makefile
mcd-pyk.py

-   Remove argument hints from generators used in Python script (to cover wider swaths of execution).
-   Make `test-random` target generate paths up to 100 bytes deep, and generate 1000 of them.
-   Remove all hints to `test-random` target about which generators to use from `Makefile`.
-   Add `--no-sort-collections` option to `krun` to take us from roughly 4s/run to 2s/run.

Generalize generators and speed up execution

---

Jenkinsfile
Makefile
README.md
kmcd-driver.md
kmcd-prelude.md
kmcd-props.md
mcd-pyk.py
tests/attacks/lucash-flap-end.mcd.expected
tests/attacks/lucash-flap-end.random.mcd.expected
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-flip-end.random.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot-end.random.mcd.expected
tests/attacks/lucash-pot.mcd.expected
tests/attacks/lucash-pot.random.mcd.expected

Run `./mcd-pyk.py --help` for information on how to run, try it yourself too!
-   `mcd-pyk.py` now prints out violating end-states/traces as soon as their found, so it can be started running and dumping to a file, and you can let it run all day and examine the log as it goes.
-   Assertion is called at the end of every transaction which does _not_ throw an exception.
-   Measures are injected only when checking the properties themselves, so that they show up at more sensible places in the logs.
I verified that we can still catch the 4 attacks with the 4 known breakages here.
I've also documented in the README how to run the random-tester, so that people can try it out.

Fail early when violation detected

---

kmcd-prelude.md
kmcd-props.md
tests/attacks/lucash-flap-end.mcd
tests/attacks/lucash-flap-end.mcd.expected
tests/attacks/lucash-flap-end.random.mcd
tests/attacks/lucash-flap-end.random.mcd.expected
tests/attacks/lucash-flip-end.mcd
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-flip-end.random.mcd
tests/attacks/lucash-flip-end.random.mcd.expected
tests/attacks/lucash-pot-end.mcd
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot-end.random.mcd
tests/attacks/lucash-pot-end.random.mcd.expected
tests/attacks/lucash-pot.mcd
tests/attacks/lucash-pot.mcd.expected
tests/attacks/lucash-pot.random.mcd
tests/attacks/lucash-pot.random.mcd.expected
tests/fixes/debtBoundDSR.mcd
tests/fixes/debtBoundDSR.mcd.expected
tests/fixes/potChiPieDai.mcd
tests/fixes/potChiPieDai.mcd.expected

Separates out "generic, immutable system configuration" in a `DEPLOY_PRELUDE` distinct from the `ATTACK_PRELUDE` rule.
Modifies the `lucash-flap-end` attack in such a way that it can be detected by the `flapMkrConsistency` property, with a couple small tweaks to harmonize the other properties with the new approach.

Add DEPLOY_PRELUDE, improve lucash-flap-end attack

---

Makefile
mcd-pyk.py

Adds an option `--emit-solidity` which attempts to emit valid solidity code which can be dumped into a testing harness for the actual Solidity implementation of this model.
This should help for conformance testing the semantics against the implementation.

Initial solidity test emission from random tester

---

.gitignore
mcd-pyk.py

I found in the python where the header and other output where and updated them to better distinguish and id each test. 
After messing with the random seed bytearray for a bit, i decided that the `i` would be sufficient for identifying which `random-test.out` run was responsible for generating which solidity test.
let me know if either of you have a better idea how to structure this.

Id solidity test output

---

kmcd-driver.md
kmcd-prelude.md
kmcd-props.md
mcd-pyk.py
tests/attacks/lucash-flap-end.mcd.expected
tests/attacks/lucash-flap-end.random.mcd.expected
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-flip-end.random.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot-end.random.mcd.expected
tests/attacks/lucash-pot.mcd.expected
tests/attacks/lucash-pot.random.mcd.expected
tests/fixes/debtBoundDSR.mcd.expected
tests/fixes/potChiPieDai.mcd.expected

-   Adds snapshotting to K definition.
-   Adds klabel declarations to some important `Event` in the log, so that we can more easily pull them out in the `mcd-pyk.py` file.
-   Changes the way contracts/addresses are wrapped in the generated solidity output.
-   Prints out a minimized state delta as a K rewrite.
-   Prints out initial attempt at assertions in the Solidity, now example emitted Solidity looks like:
```
// Test Run
ADMIN.Vat_rely(address(GemJoin_gold));
ADMIN.Spot_setPrice("gold", 1);
ADMIN.Flip_gold_rely(address(End));
ADMIN.Vat_file("Line", 1000000000000);
ADMIN.Vat_file("spot", "gold", 3000000000);
ADMIN.Vat_file("line", "gold", 1000000000000);
ADMIN.Vow_file("bump", 1000000000);
ADMIN.Vow_file("hump", 0);
ADMIN.Gem_gold_mint(address(Alice), 20); …
```

Initial assertions in emitted Solidity

---

mcd-pyk.py

Doing some brute find and replace to eliminate variable naming conflicts in the solidity tests.
Current example output:
```
------------
// Test Run
admin.vat_rely(address(goldJoin));
admin.spotter_setPrice("gold", 1);
admin.goldFlip_rely(address(end));
admin.vat_file("Line", 1000000000000);
admin.vat_file("spot", "gold", 3000000000);
admin.vat_file("line", "gold", 1000000000000);
admin.vow_file("bump", 1000000000);
admin.vow_file("hump", 0);
admin.Gem_gold_mint(address(alice), 20);
admin.Gem_gold_mint(address(bobby), 20);
alice.vat_hope(address(pot));
alice.vat_hope(address(goldFlip));
alice.vat_hope(address(end));
bobby.vat_hope(address(pot));
bobby.vat_hope(address(goldFlip));
bobby.vat_hope(address(end));
alice.goldJoin_join(address(alice), 10);
bobby.goldJoin_join(address(bobby), …
```

variablize solidty and assertions to avoid naming conflicts

---

mcd-pyk.py

This should wait for #168 and #167 before merge (to address merge conflicts), but morally should be reviewed separately.
-   Simplifies the logic of flattening collections in several places in `mcd-pyk.py`.
-   Fixes the violation checking in `mcd-pyk.py`.
-   Handles more assertion generation when there is a mapping update during execution.
An example of a mapping update looks like:
```
assertTrue( vat.can(address(bobby), address(end)) != 0 );
assertTrue( vat.can(address(bobby), address(alice)) != 0 );
assertTrue( vat.can(address(bobby), address(goldFlip)) != 0 );
assertTrue( vat.can(address(bobby), address(pot)) != 0 );
assertTrue( vat.can(address(alice), address(end)) != 0 );
assertTrue( vat.can(address(alice), address(goldFlip)) != 0 );
assertTrue( vat.can(address(alice), …
```

Handle more assertions, fixes to violation checking

---

.gitmodules
cat.md
dai.md
end.md
flap.md
flip.md
flop.md
gem.md
jug.md
pot.md
spot.md
vat.md

Many places in the solidity use `uint ...`, which is an implicit positivity constraint on the inputs to the functions.
This adds those constraints to the model.
This also adds `dss` repo as a submodule for convenience of conformance testing. This means that this submodule needs to be updated periodically and any updates to the model added in.

Implicit lower bounds on rule inputs

---

Makefile
cat.md
dai.md
end.md
flap.md
flip.md
flop.md
gem.md
join.md
jug.md
kmcd-data.md
kmcd-driver.md
kmcd-prelude.md
kmcd-props.md
pot.md
spot.md
tests/attacks/blocked-flop.mcd
tests/attacks/lucash-flap-end.mcd
tests/attacks/lucash-flip-end.mcd
tests/attacks/lucash-pot-end.mcd
tests/attacks/lucash-pot.mcd
tests/fixes/debtBoundDSR.mcd
tests/fixes/potChiPieDai.mcd
vat.md
vow.md

This is to make it easier to change out the underlying representation of Wad/Rad/Ray in the semantics without having to change every call-site. It will also provide stronger information at each call-site about the sorts of all quantities.

Separate out representation of Wad/Rad/Ray

---

cat.md
end.md
flap.md
flip.md
flop.md
kmcd-data.md
kmcd-prelude.md
kmcd-props.md
tests/attacks/blocked-flop.mcd.expected
tests/attacks/lucash-flap-end.mcd.expected
tests/attacks/lucash-flap-end.random.mcd.expected
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-flip-end.random.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot-end.random.mcd.expected
tests/attacks/lucash-pot.mcd.expected
tests/attacks/lucash-pot.random.mcd.expected
tests/fixes/debtBoundDSR.mcd.expected
tests/fixes/potChiPieDai.mcd.expected
vat.md

Blocked on #173 
This makes the types stronger for each of `Wad/Ray/Rad`, by making them wrapped rationals instead of just sort synonyms for rationals.
The benefit here is that we get sort-checking now for each operation we use.

Wrapped rat representation for `Wad/Ray/Rad`

---

cat.md
dai.md
end.md
flap.md
flip.md
flop.md
gem.md
join.md
jug.md
kmcd-data.md
kmcd-driver.md
kmcd-prelude.md
kmcd-props.md
pot.md
spot.md
vat.md
vow.md

There were still some issues with changing the underlying representation of these data-types, so this refactors to make it easier. Basic changes include:
-   Removal of `0{Wad,Ray,Rad}` and `1{Wad,Ray,Rad}` in favor of `{wad,ray,rad}(0)` and `{wad,ray,rad}(1)`.
-   Avoid names `WAD`, `RAY`, and `RAD` for variable names.
-   Switch away from directly putting rationals in configurations of `flip`, `flap`, and `flop`.
-   Add quantities `WAD`, `RAY`, and `RAD` for convenience later.

Clean separation of representation of Wad/Ray/Rad

---

Dockerfile
Jenkinsfile
Makefile

~Not ready for merge.~
@daimesava and @kmbarry1 this is ready for review now. It makes it so that we use the K dockerhub image on CI jobs, for the purpose of skipping the K build step.
If CircleCI is able to take advantage of Dockerhub images, then this may be helpful there too.

Use K Dockerhub images on CI

---

mcd-pyk.py
vat.md

-   Handles maps with `CDPID`s as keys in generating assertions.
-   Switches to generating code for `FInt` correctly.
-   Adds functions `solidityArgs` and `solidityKeys` which make it easier to build Solidity function calls for both method calls and assertion building.
-   Refactors `stateAssertions` to be recursive, so that traversing the existing state and building assertions is simpler.

Improve random testing

---

Makefile
cat.md
end.md
fixed-int.md
flip.md
flop.md
jug.md
kmcd-data.md
kmcd-driver.md
kmcd-prelude.md
kmcd-props.md
spot.md
tests/attacks/blocked-flop.mcd.expected
tests/attacks/lucash-flap-end.mcd.expected
tests/attacks/lucash-flap-end.random.mcd.expected
tests/attacks/lucash-flip-end.mcd.expected
tests/attacks/lucash-flip-end.random.mcd.expected
tests/attacks/lucash-pot-end.mcd.expected
tests/attacks/lucash-pot-end.random.mcd.expected
tests/attacks/lucash-pot.mcd.expected
tests/attacks/lucash-pot.random.mcd.expected
tests/fixes/debtBoundDSR.mcd.expected
tests/fixes/potChiPieDai.mcd.expected
vat.md

-   Rename all occurances of `ILKID` to `ILK_ID` for consistency (easier grep-ability).
-   Add file parameters to some of the contracts that were not present before.
-   Some contracts get "default initialization" of their data-structures. Ideally we would have a solution to always do this, but we don't. So for now, I've handled the few cases that show up.
-   Removes all the `Unused variable` warnings that show up with newest K.

Updates before adding constructors/deploy logic

---

Jenkinsfile
kmcd-prelude.md
mcd-pyk.py

Major changes include:
-   Skip generating calls for deployment or constructor function calls.
-   Choose only addresses which make sense for randomly generated transactions (non-ADMIN non-MCD-contract addresses).
-   Correct the name used for pot `pie` and `Pie` fields in solidity generation.

Solidity generation fixes

---

kmcd-prelude.md
mcd-pyk.py
tests/solidity-test/MkrMcdSpecSolTests.sol

This wraps statements that should succeed in `assertTrue(...);`, in preparation for supporting asserting reverts.
This subsumes https://github.com/makerdao/mkr-mcd-spec-sol-tests/pull/4.
-    The test harness returns `true` or `false` depending on whether a call succeeded or not.
-    All generated statements that should succeed are wrapped in an `assertTrue`.
-    A call to `GemJoin "MKR"` which is generated by `kmcd-prelude.md` is removed.

Use assertions for all statements

---

fixed-int.md
kmcd-driver.md
kmcd-prelude.md
vat.md

These are a few simplifications to the semantics I found which help my local work with symbolic reasoning.
- Make `wish` a non-contextual function, so that it's possible to use it over the pre/post states in proofs.
- Mark `wards` as functional.
- Add `domains.md` explicit import.
- `makeCall` no longer defaults to throwing an exception, because `checkLock` and `checkAuth` handle that.

Simplifications for symbolic reasoning
